In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.datasets import load_wine

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score

from sklearn.metrics import confusion_matrix,classification_report

from sklearn.model_selection import GridSearchCV

In [ ]:
# 1.

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Iris.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/iris",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)



X = df.drop("Species", axis=1)
y = df["Species"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test,y_pred)

/tmp/ipykernel_749/3511604940.py:12: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'iris' dataset.

In [ ]:
print(cm
)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

# 2. GridSearchCV for Customer Segmentation Prediction

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "marketing_campaign.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "imakash3011/customer-personality-analysis",
  file_path,
  pandas_kwargs={'sep': '\t'}
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:")
display(df.head())

/tmp/ipykernel_749/1346689784.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'customer-personality-analysis' dataset.
First 5 records:

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [ ]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [ ]:
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [ ]:
y = df['Response']
X = df.drop(columns=['Response', 'ID'])

In [ ]:
# train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1792 entries, 1090 to 952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year_Birth           1792 non-null   int64
 1   Education            1792 non-null   object
 2   Marital_Status       1792 non-null   object
 3   Income               1771 non-null   float64
 4   Kidhome              1792 non-null   int64
 5   Teenhome             1792 non-null   int64
 6   Dt_Customer          1792 non-null   object
 7   Recency              1792 non-null   int64
 8   MntWines             1792 non-null   int64
 9   MntFruits            1792 non-null   int64
 10  MntMeatProducts      1792 non-null   int64
 11  MntFishProducts      1792 non-null   int64
 12  MntSweetProducts     1792 non-null   int64
 13  MntGoldProds         1792 non-null   int64
 14  NumDealsPurchases    1792 non-null   int64
 15  NumWebPurchases      1792 non-null   int64
 16  NumCatalogPurchases  1792 non-null   int64
 17  NumStorePurchases    1792 non-null   int64
 18  NumWebVisitsMonth    1792 non-null   int64
 19  AcceptedCmp3         1792 non-null   int64
 20  AcceptedCmp4         1792 non-null   int64
 21  AcceptedCmp5         1792 non-null   int64
 22  AcceptedCmp1         1792 non-null   int64
 23  AcceptedCmp2         1792 non-null   int64
 24  Complain             1792 non-null   int64
 25  Z_CostContact        1792 non-null   int64
 26  Z_Revenue            1792 non-null   int64
dtypes: float64(1), int64(23), object(3)
memory usage: 392.0+ KB

In [ ]:
df['Dt_Customer']

0       04-09-2012
1       08-03-2014
2       21-08-2013
3       10-02-2014
4       19-01-2014
           ...
2235    13-06-2013
2236    10-06-2014
2237    25-01-2014
2238    24-01-2014
2239    15-10-2012
Name: Dt_Customer, Length: 2240, dtype: object

In [ ]:
cat_cols = [
    'Education',
    'Marital_Status', 'Dt_Customer'
]

num_cols = X_train.select_dtypes(
    include=['int64', 'float64']
).columns.tolist()

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

from sklearn.preprocessing import OneHotEncoder

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(
        handle_unknown='ignore',
        sparse_output=False
    ))
])

In [ ]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

default_knn = Pipeline([
    ('preprocessor', preprocessor),
    ('knn', KNeighborsClassifier())
])

In [ ]:
default_knn.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Year_Birth', 'Income',
                                                   'Kidhome', 'Teenhome',
                                                   'Recency', 'MntWines',
                                                   'MntFruits',
                                                   'MntMeatProducts',
                                                   'MntFishProducts',
                                                   'MntSweetProducts',
                                                   'MntGoldProds',
                                                   'NumDealsPurchases',
                                                   'NumWebPurchases',
                                                   'NumCatalogPurchases',
                                                   'NumStorePurchases',
                                                   'NumWebVisitsMonth',
                                                   'AcceptedCmp3',
                                                   'AcceptedCmp4',
                                                   'AcceptedCmp5',
                                                   'AcceptedCmp1',
                                                   'AcceptedCmp2', 'Complain',
                                                   'Z_CostContact',
                                                   'Z_Revenue']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Education',
                                                   'Marital_Status',
                                                   'Dt_Customer'])])),
                ('knn', KNeighborsClassifier())])

In [ ]:
y_pred_default = default_knn.predict(X_test)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy:",
      accuracy_score(y_test, y_pred_default))

print("Precision:",
      precision_score(
          y_test,
          y_pred_default,
          average='weighted',
          zero_division=0
      ))

print("Recall:",
      recall_score(
          y_test,
          y_pred_default,
          average='weighted',
          zero_division=0
      ))

print("F1:",
      f1_score(
          y_test,
          y_pred_default,
          average='weighted',
          zero_division=0
      ))

Accuracy: 0.8727678571428571
Precision: 0.8547765573620753
Recall: 0.8727678571428571
F1: 0.8546230751781377

In [ ]:
param_grid = {
    'knn__n_neighbors': range(1, 31),
    'knn__metric': ['euclidean', 'manhattan'],
    'knn__weights': ['uniform', 'distance']
}

from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator=default_knn,
    param_grid=param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1
)

In [ ]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['Year_Birth',
                                                                          'Income',
                                                                          'Kidhome',
                                                                          'Teenhome',
                                                                          'Recency',
                                                                          'MntWines',
                                                                          'MntFruits',
                                                                          'MntMeatProducts',
                                                                          'MntFishProducts',
                                                                          'MntSweetProducts',
                                                                          'MntGoldProds',
                                                                          'NumDealsPurc...
                                                                          'Z_CostContact',
                                                                          'Z_Revenue']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('encoder',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['Education',
                                                                          'Marital_Status',
                                                                          'Dt_Customer'])])),
                                       ('knn', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'knn__metric': ['euclidean', 'manhattan'],
                         'knn__n_neighbors': range(1, 31),
                         'knn__weights': ['uniform', 'distance']},
             scoring='f1_weighted')

In [ ]:
grid_search.best_params_

{'knn__metric': 'euclidean', 'knn__n_neighbors': 7, 'knn__weights': 'distance'}

In [ ]:
grid_search.best_score_

np.float64(0.8584174542146819)

In [ ]:
best_model = grid_search.best_estimator_

In [ ]:
y_pred_tuned = best_model.predict(X_test)

In [ ]:
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)

In [ ]:
tuned_accuracy

0.875

In [ ]:
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)

tuned_precision = precision_score(
    y_test,
    y_pred_tuned,
    average='weighted',
    zero_division=0
)

tuned_recall = recall_score(
    y_test,
    y_pred_tuned,
    average='weighted',
    zero_division=0
)

tuned_f1 = f1_score(
    y_test,
    y_pred_tuned,
    average='weighted',
    zero_division=0
)

print("Tuned KNN")
print("Accuracy :", tuned_accuracy)
print("Precision:", tuned_precision)
print("Recall   :", tuned_recall)
print("F1-score :", tuned_f1)

Tuned KNN
Accuracy : 0.875
Precision: 0.8581200276720857
Recall   : 0.875
F1-score : 0.8579110485504025

In [ ]:
comparison = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-score'],
    'Default KNN': [
        accuracy_score(y_test, y_pred_default),
        precision_score(y_test, y_pred_default,
                        average='weighted', zero_division=0),
        recall_score(y_test, y_pred_default,
                     average='weighted', zero_division=0),
        f1_score(y_test, y_pred_default,
                 average='weighted', zero_division=0)
    ],
    'Tuned KNN': [
        tuned_accuracy,
        tuned_precision,
        tuned_recall,
        tuned_f1
    ]
})

comparison

      Metric  Default KNN  Tuned KNN
0   Accuracy     0.872768   0.875000
1  Precision     0.854777   0.858120
2     Recall     0.872768   0.875000
3   F1-score     0.854623   0.857911