# Implementationof perceptron from scratch

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")

In [2]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3)* 1e-4
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z>0, 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y
    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
    print(f"X with bias: {X_with_bias}/n")

    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch >> {epoch}")
      print("--"*10)

      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value after forward pass: {y_hat}")

      error = self.y - y_hat
      print(f"error: {error}")

      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error) # weight updatation
      print(f"updated weights after epoch: {epoch}/{self.epochs}: {self.weights}")


  def predict(self, X):
    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights) # prediction will come from the activation function, as weights has been updated in fit()

In [3]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [6]:
X = AND.drop("y", axis=1)
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [7]:
model = Perceptron(eta = 0.1, epochs = 10)
model.fit(X,y)

X with bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]/n
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: [0 1 0 0]
error: 0    0
1   -1
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 0/10: [9.99204981e-02 2.43441530e-05 2.91081111e-06]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: [0 1 1 1]
error: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: [-7.95018884e-05 -9.99756558e-02  2.00002911e-01]
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: [0 0 0 0]
error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: [9.99204981e-02 2.43441530e-05 1.00002911e-01]
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: [0 0 0 0]
error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: [1.99920498e-01 1.00024344e-01 2.91081111e-06]
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: [0 1 1 1]
error: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: [9.99204981e-02 2.43441530e-05 2.00002911e-01]
--------------------
for epoch >> 5
--------------------
predicted value after forward pass: [0 0 0 0]
error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 5/10: [0.1999205  0.10002434 0.10000291]
--------------------
for epoch >> 6
--------------------
predicted value after forward pass: [0 1 1 1]
error: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 6/10: [9.99204981e-02 2.43441530e-05 3.00002911e-01]
--------------------
for epoch >> 7
--------------------
predicted value after forward pass: [0 0 0 0]
error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 7/10: [0.1999205  0.10002434 0.20000291]
--------------------
for epoch >> 8
--------------------
predicted value after forward pass: [0 0 0 1]
error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 8/10: [0.1999205  0.10002434 0.20000291]
--------------------
for epoch >> 9
--------------------
predicted value after forward pass: [0 0 0 1]
error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 9/10: [0.1999205  0.10002434 0.20000291]

In [8]:
model.predict(X)

array([0, 0, 0, 1])

# Saving model

In [9]:
import os
dir_ = "Perceptron_model"
os.makedirs(dir_, exist_ok=True)
filename = os.path.join(dir_, "AND.model")
joblib.dump(model, filename)

['Perceptron_model/AND.model']

In [10]:
# load the model from drive:

loaded_model = joblib.load(filename)
result = loaded_model.predict(X)
result

array([0, 0, 0, 1])